name: 'Build deplibs posix'
description: 'Build deplibs posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

outputs:
  artifact-path:
    description: 'built file'
    value: ${{ steps.create-artifact.outputs.artifact-path }}

runs:
  using: "composite"
  steps:

  - name: Install glew
    shell: bash
    run: |
      cd ${GITHUB_WORKSPACE}
      BASEDIR=${{ inputs.basedir }}
      bash macos_arm64/build_glew.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  # - name: Install lcms2
  #   shell: bash
  #   run: |
  #     cd ${GITHUB_WORKSPACE}
  #     BASEDIR=${{ inputs.basedir }}
  #     bash macos_arm64/build_lcms2.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  # - name: Install fftw3
  #   shell: bash
  #   run: |
  #     cd ${GITHUB_WORKSPACE}
  #     BASEDIR=${{ inputs.basedir }}
  #     bash macos_arm64/build_fftw3.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  # - name: Install boost
  #   shell: bash
  #   run: |
  #     cd ${GITHUB_WORKSPACE}
  #     BASEDIR=${{ inputs.basedir }}
  #     bash macos_arm64/build_boost.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  # - name: Install CGAL
  #   shell: bash
  #   run: |
  #     cd ${GITHUB_WORKSPACE}
  #     BASEDIR=${{ inputs.basedir }}
  #     bash macos_arm64/build_cgal.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  - name: Create deplibs tarball
    id: create-artifact
    shell: bash
    env:
      ARTIFACT_NAME: deplibs_${{ runner.os }}_${{ runner.arch }}.tar.bz2
    run: |
      set -eux
      BASEDIR=${{ inputs.basedir }}
      # Clean-up
      rm -rf $BASEDIR/tmp
      cd $BASEDIR/..
      tar cjf ${GITHUB_WORKSPACE}/${ARTIFACT_NAME} target
      cd ${GITHUB_WORKSPACE}
      ls -lh ${GITHUB_WORKSPACE}/${ARTIFACT_NAME}
      echo "artifact-path=${GITHUB_WORKSPACE}/${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
