name: 'Build deplibs windows'
description: 'Build deplibs windows'

inputs:
  basedir:
     description: 'base dir'
     required: true

# outputs:
#   artifact-path:
#     description: 'built file'
#     value: ${{ steps.create-artifact.outputs.artifact-path }}

runs:
  using: "composite"
  steps:

  - name: Build glew
    shell: cmd
    run: |
      REM cd ${GITHUB_WORKSPACE}
      build_deplibs_windows/build_glew.bat ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}
