name: 'Build deplibs windows'
description: 'Build deplibs windows'

inputs:
  basedir:
     description: 'base dir'
     required: true

outputs:
  artifact-path:
    description: 'built file'
    value: ${{ steps.create-artifact.outputs.artifact-path }}

runs:
  using: "composite"
  steps:

  # - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
  #   shell: powershell
  #   run: |
  #     $VS_BTOOLS_EXE="vs_buildtools.exe"
  #     $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
  #     Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
  #     Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
  #     "--add", "Microsoft.VisualStudio.Component.VC.140", `
  #     "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
  #     "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru

  - name: Build glew
    shell: cmd
    run: |
      REM cd ${GITHUB_WORKSPACE}
      build_deplibs_windows/build_glew.bat ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

  # - name: Build lcms2
  #   shell: cmd
  #   run: |
  #     REM cd ${GITHUB_WORKSPACE}
  #     build_deplibs_windows/build_lcms2.bat ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

  # - name: Build fftw
  #   shell: cmd
  #   run: |
  #     REM cd ${GITHUB_WORKSPACE}
  #     build_deplibs_windows/build_fftw.bat ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

  # - name: Build lzma
  #   shell: cmd
  #   run: |
  #     REM cd ${GITHUB_WORKSPACE}
  #     build_deplibs_windows/build_lzma.bat ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

  - name: Create deplibs tarball
    id: create-artifact
    shell: cmd
    env:
      ARTIFACT_NAME: deplibs_${{ runner.os }}_${{ runner.arch }}.tar.bz2
    run: |
      SET BASEDIR=${{ inputs.basedir }}
      rd /s /q %BASEDIR%\tmp
      cd %BASEDIR%\..
      tar cjf %GITHUB_WORKSPACE%\%ARTIFACT_NAME% target
      dir %GITHUB_WORKSPACE%\%ARTIFACT_NAME%
      echo "artifact-path=%GITHUB_WORKSPACE%\%ARTIFACT_NAME%" >> %GITHUB_OUTPUT%
