name: Build and release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

###############################################

jobs:
  build_mac_arm64:
    name: "MacOS 14 arm64 clang"
    runs-on: macos-14
    steps:

    - name: Install prerequisites
      run: |
        brew install automake

    - uses: actions/checkout@v4

    - name: Build deplibs
      id: build-artifact
      uses: ./build_deplibs_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deplibs_linux_x64
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  build_mac_x64:
    name: "MacOS 12 intel clang"
    runs-on: macos-12
    steps:

    - name: Install prerequisites
      run: |
        brew install automake

    - uses: actions/checkout@v4

    - name: Build deplibs
      id: build-artifact
      uses: ./build_deplibs_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deplibs_linux_x64
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  build_linux_x64:
    name: "Ubuntu x64 gcc"
    runs-on: ubuntu-22.04
    steps:

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev libglu1-mesa-dev xvfb mesa-utils
        # libgles2-mesa-dev libegl1-mesa-dev

    - uses: actions/checkout@v4

    - name: Build deplibs
      id: build-artifact
      uses: ./build_deplibs_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deplibs_linux_x64
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  # build_win_x64:
  #   name: "Windows intel msvc"
  #   runs-on: windows-2019
  #   steps:

  #   steps:
  #   - name: Install prerequisite
  #     run: |
  #       choco install -r wget

  #   - uses: actions/checkout@v4



###############################################

  # release_build:
  #   needs: [build_mac_arm64,build_mac_intel]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download All Artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       path: artifacts
  #       merge-multiple: true
  #   - run: |
  #       ls -lR

  #   - name: Release
  #     uses: softprops/action-gh-release@v2
  #     if: startsWith(github.ref, 'refs/tags/')
  #     with:
  #       files: artifacts/*.tar.bz2
