name: Build Windows test1

on:
  push:
    # branches:
    #   - main

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022

    steps:

    - name: Install prerequisite
      run: |
        choco install -r wget

    - uses: actions/checkout@v4

    # - name: Add MSBuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build deplibs
      id: build-artifact
      uses: ./build_deplibs_windows
      with:
        basedir: ${{ github.workspace }}\target

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deplibs_windows_x64
        path: ${{ steps.build-artifact.outputs.artifact-path }}
        
